-- Royal Technology Solutions (RoyalDB)
-- CIS421 Unit 6 - Introduction to SQL
-- FINAL IMPLEMENTATION + VALIDATION VERSION
-- PostgreSQL 18 / DB01 / Royal1.Local
-- Purpose: create RoyalDB schema, load test data, demonstrate SQL,
-- and document the final integrity, RBAC, least-privilege, and
-- backup/recovery validation completed in the lab.

DROP TABLE IF EXISTS ticket_assignment;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS technician;
DROP TABLE IF EXISTS contract;
DROP TABLE IF EXISTS device;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(120) NOT NULL,
    contact_first_name VARCHAR(60) NOT NULL,
    contact_last_name VARCHAR(60) NOT NULL,
    contact_email VARCHAR(120) NOT NULL,
    contact_phone VARCHAR(25),
    customer_status VARCHAR(20) NOT NULL
        CHECK (customer_status IN ('Active','Inactive')),
    created_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE location (
    location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customer(customer_id),
    location_name VARCHAR(100) NOT NULL,
    address_line1 VARCHAR(120) NOT NULL,
    address_line2 VARCHAR(120),
    city VARCHAR(60) NOT NULL,
    state VARCHAR(30) NOT NULL,
    postal_code VARCHAR(15) NOT NULL,
    location_phone VARCHAR(25),
    location_status VARCHAR(20) NOT NULL
        CHECK (location_status IN ('Active','Inactive'))
);

CREATE TABLE device (
    device_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES location(location_id),
    device_name VARCHAR(100) NOT NULL,
    device_type VARCHAR(40) NOT NULL,
    manufacturer VARCHAR(60),
    model VARCHAR(60),
    serial_number VARCHAR(80),
    ip_address VARCHAR(45),
    operating_system VARCHAR(100),
    purchase_date DATE,
    warranty_expiration DATE,
    device_status VARCHAR(20) NOT NULL
        CHECK (device_status IN ('Active','Inactive','Maintenance','Retired'))
);

CREATE TABLE contract (
    contract_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customer(customer_id),
    contract_type VARCHAR(60) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    service_level VARCHAR(20) NOT NULL
        CHECK (service_level IN ('Standard','Priority','Premium')),
    contract_status VARCHAR(20) NOT NULL
        CHECK (contract_status IN ('Active','Pending','Expired','Terminated')),
    monthly_rate NUMERIC(10,2) NOT NULL CHECK (monthly_rate >= 0),
    CHECK (end_date >= start_date)
);

CREATE TABLE technician (
    technician_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    phone VARCHAR(25),
    job_title VARCHAR(80) NOT NULL,
    skill_level VARCHAR(20) NOT NULL
        CHECK (skill_level IN ('Level 1','Level 2','Level 3','Specialist')),
    technician_status VARCHAR(20) NOT NULL
        CHECK (technician_status IN ('Active','Inactive','Leave'))
);

CREATE TABLE ticket (
    ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customer(customer_id),
    device_id INTEGER REFERENCES device(device_id),
    ticket_title VARCHAR(150) NOT NULL,
    ticket_description TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL
        CHECK (priority IN ('Low','Medium','High','Critical')),
    ticket_status VARCHAR(20) NOT NULL
        CHECK (ticket_status IN ('New','Open','In Progress','Pending','Resolved','Closed')),
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_date TIMESTAMP,
    closed_date TIMESTAMP,
    CHECK (resolved_date IS NULL OR resolved_date >= created_date),
    CHECK (closed_date IS NULL OR closed_date >= created_date)
);

CREATE TABLE ticket_assignment (
    assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES ticket(ticket_id),
    technician_id INTEGER NOT NULL REFERENCES technician(technician_id),
    assigned_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assignment_role VARCHAR(60) NOT NULL,
    hours_worked NUMERIC(6,2) CHECK (hours_worked IS NULL OR hours_worked >= 0),
    assignment_status VARCHAR(20) NOT NULL
        CHECK (assignment_status IN ('Assigned','In Progress','Completed','Escalated'))
);

-- Test data
INSERT INTO customer
(company_name, contact_first_name, contact_last_name, contact_email, contact_phone, customer_status, created_date)
VALUES
('Northstar Medical Group','Alicia','Brown','alicia.brown@example.com','612-555-0101','Active','2026-07-01'),
('Lakeview Manufacturing','Marcus','Hill','marcus.hill@example.com','651-555-0102','Active','2026-07-15'),
('Global Learning Partners','Renee','Cole','renee.cole@example.com','763-555-0103','Active','2026-08-01');

INSERT INTO location
(customer_id, location_name, address_line1, address_line2, city, state, postal_code, location_phone, location_status)
VALUES
(1,'Northstar Headquarters','100 Health Way',NULL,'Minneapolis','MN','55401','612-555-0201','Active'),
(2,'Lakeview Plant 1','225 Industry Ave','Building A','St. Paul','MN','55101','651-555-0202','Active'),
(3,'Global Learning Office','410 Campus Blvd',NULL,'Bloomington','MN','55420',NULL,'Active');

INSERT INTO device
(location_id, device_name, device_type, manufacturer, model, serial_number, ip_address, operating_system, purchase_date, warranty_expiration, device_status)
VALUES
(1,'NS-FILE01','Server','Dell','PowerEdge','NS10001','10.10.1.20','Windows Server','2024-03-15','2027-03-15','Active'),
(1,'NS-WS014','Workstation','HP','EliteDesk','NS20014','10.10.1.114','Windows 11','2025-01-10','2028-01-10','Active'),
(2,'LV-SW01','Network Device','Cisco','Catalyst','LV30001','10.20.1.2',NULL,'2023-11-05','2026-11-05','Maintenance'),
(3,'GL-LT022','Laptop','Lenovo','ThinkPad','GL40022','10.30.1.122','Windows 11','2025-06-20',NULL,'Active');

INSERT INTO contract
(customer_id, contract_type, start_date, end_date, service_level, contract_status, monthly_rate)
VALUES
(1,'Managed IT Services','2026-01-01','2026-12-31','Premium','Active',4500.00),
(2,'Infrastructure Support','2026-03-01','2027-02-28','Priority','Active',3200.00),
(3,'Help Desk Services','2026-08-01','2027-07-31','Standard','Active',1800.00);

INSERT INTO technician
(first_name, last_name, email, phone, job_title, skill_level, technician_status)
VALUES
('Jordan','Lee','jordan.lee@royaltech.example','612-555-1001','Service Desk Technician','Level 1','Active'),
('Morgan','Reed','morgan.reed@royaltech.example','612-555-1002','Systems Engineer','Level 3','Active'),
('Casey','Grant','casey.grant@royaltech.example',NULL,'Security Engineer','Specialist','Active');

INSERT INTO ticket
(customer_id, device_id, ticket_title, ticket_description, priority, ticket_status, created_date, resolved_date, closed_date)
VALUES
(1,1,'File server access failure','Users cannot reach a shared department folder.','Critical','In Progress','2026-09-01 08:15:00',NULL,NULL),
(2,3,'Switch port instability','Intermittent connectivity reported on production floor.','High','Open','2026-09-01 10:30:00',NULL,NULL),
(3,NULL,'Microsoft 365 sign-in issue','User receives repeated authentication prompts.','Medium','New','2026-09-02 09:10:00',NULL,NULL),
(1,2,'Workstation printer mapping','Printer mapping was restored for the user.','Low','Resolved','2026-08-28 13:00:00','2026-08-28 14:20:00',NULL);

INSERT INTO ticket_assignment
(ticket_id, technician_id, assigned_date, assignment_role, hours_worked, assignment_status)
VALUES
(1,2,'2026-09-01 08:25:00','Primary Engineer',2.50,'In Progress'),
(2,2,'2026-09-01 10:45:00','Network Troubleshooting',1.75,'Assigned'),
(3,1,'2026-09-02 09:20:00','Service Desk Owner',NULL,'Assigned'),
(1,3,'2026-09-01 09:00:00','Security Review',1.00,'Completed');

-- 1. SELECT / FROM: list active customers
SELECT customer_id, company_name, contact_email
FROM customer
WHERE customer_status = 'Active';

-- 2. WHERE: high-priority and critical tickets
SELECT ticket_id, ticket_title, priority, ticket_status
FROM ticket
WHERE priority IN ('High','Critical');

-- 3. BETWEEN: contracts starting during calendar year 2026
SELECT contract_id, customer_id, start_date, end_date, service_level
FROM contract
WHERE start_date BETWEEN '2026-01-01' AND '2026-12-31';

-- 4. IN: tickets in active workflow states
SELECT ticket_id, ticket_title, ticket_status
FROM ticket
WHERE ticket_status IN ('New','Open','In Progress','Pending');

-- 5. LIKE: locate devices whose names begin with NS-
SELECT device_id, device_name, device_type
FROM device
WHERE device_name LIKE 'NS-%';

-- 6. IS NULL: tickets that are not tied to a physical device
SELECT ticket_id, customer_id, ticket_title
FROM ticket
WHERE device_id IS NULL;

-- 7. JOIN: show tickets with customer names
SELECT t.ticket_id,
       c.company_name,
       t.ticket_title,
       t.priority,
       t.ticket_status
FROM ticket t
JOIN customer c ON c.customer_id = t.customer_id
ORDER BY t.ticket_id;

-- 8. Multi-table JOIN: show technician assignments
SELECT ta.assignment_id,
       t.ticket_id,
       t.ticket_title,
       tech.first_name,
       tech.last_name,
       ta.assignment_role,
       ta.assignment_status
FROM ticket_assignment ta
JOIN ticket t ON t.ticket_id = ta.ticket_id
JOIN technician tech ON tech.technician_id = ta.technician_id
ORDER BY ta.assignment_id;

-- 9. Subquery: tickets for customers with active service contracts
SELECT ticket_id, customer_id, ticket_title, ticket_status
FROM ticket
WHERE customer_id IN (
    SELECT customer_id
    FROM contract
    WHERE contract_status = 'Active'
);

-- 10. INSERT example: create a new support ticket
INSERT INTO ticket
(customer_id, device_id, ticket_title, ticket_description, priority, ticket_status)
VALUES
(3, NULL, 'VPN connection request',
 'Customer cannot establish a remote VPN session.',
 'Medium', 'New');

-- 11. UPDATE example: change ticket status
UPDATE ticket
SET ticket_status = 'In Progress'
WHERE ticket_id = 3;

-- 12. Verification query
SELECT ticket_id, ticket_title, priority, ticket_status, device_id
FROM ticket
ORDER BY ticket_id;


-- =====================================================================
-- FINAL PROJECT VALIDATION / SECURITY ADDENDUM
-- Added after implementation testing.
--
-- IMPORTANT:
-- Messages such as "violates check constraint", "violates foreign key
-- constraint", and "permission denied" in the TEST sections below are
-- EXPECTED results. They demonstrate that RoyalDB is enforcing the
-- intended integrity and least-privilege controls.
-- =====================================================================

-- 13. Final schema verification: should return exactly seven tables.
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

-- 14. Final row-count verification.
-- After the Unit 6 INSERT example above, expected counts are:
-- customer=3, location=3, device=4, contract=3,
-- technician=3, ticket=5, ticket_assignment=4.
SELECT 'customer' AS table_name, COUNT(*) FROM customer
UNION ALL
SELECT 'location', COUNT(*) FROM location
UNION ALL
SELECT 'device', COUNT(*) FROM device
UNION ALL
SELECT 'contract', COUNT(*) FROM contract
UNION ALL
SELECT 'technician', COUNT(*) FROM technician
UNION ALL
SELECT 'ticket', COUNT(*) FROM ticket
UNION ALL
SELECT 'ticket_assignment', COUNT(*) FROM ticket_assignment;

-- 15. Corrected Customer-Ticket-Device JOIN.
-- The physical PostgreSQL schema uses snake_case identifiers
-- (customer_id, ticket_id, device_id), not conceptual CamelCase names.
SELECT
    t.ticket_id,
    c.company_name,
    t.ticket_title,
    t.priority,
    t.ticket_status,
    d.device_name
FROM ticket AS t
JOIN customer AS c
    ON t.customer_id = c.customer_id
LEFT JOIN device AS d
    ON t.device_id = d.device_id
ORDER BY t.ticket_id;

-- 16. Ticket Assignment bridge validation.
-- Ticket 1 should show more than one technician, demonstrating the
-- many-to-many Ticket-to-Technician relationship through the bridge table.
SELECT
    t.ticket_id,
    t.ticket_title,
    tech.first_name,
    tech.last_name,
    ta.assignment_role,
    ta.assignment_status,
    ta.hours_worked
FROM ticket AS t
JOIN ticket_assignment AS ta
    ON t.ticket_id = ta.ticket_id
JOIN technician AS tech
    ON ta.technician_id = tech.technician_id
ORDER BY t.ticket_id, tech.last_name;

-- =====================================================================
-- EXPECTED-DENIAL INTEGRITY TESTS
-- Run these statements INDIVIDUALLY when demonstrating validation.
-- They are intentionally invalid and SHOULD FAIL.
-- Do not "fix" the resulting error messages; the denials are the evidence.
-- =====================================================================

-- 17. EXPECTED DENIAL: CHECK constraint test.
-- Expected: rejected by ticket_priority_check because 'Urgent'
-- is not an approved priority. No row should be inserted.
/*
INSERT INTO ticket (
    customer_id, device_id, ticket_title, ticket_description,
    priority, ticket_status, created_date
)
VALUES (
    1, NULL, 'Invalid Priority Test',
    'This record should be rejected by the database.',
    'Urgent', 'New', CURRENT_TIMESTAMP
);
*/

-- 18. EXPECTED DENIAL: foreign-key integrity test.
-- Expected: rejected by ticket_customer_id_fkey because customer 9999
-- does not exist. No row should be inserted.
/*
INSERT INTO ticket (
    customer_id, device_id, ticket_title, ticket_description,
    priority, ticket_status, created_date
)
VALUES (
    9999, NULL, 'Invalid Customer Test',
    'This record should be rejected because the customer does not exist.',
    'High', 'New', CURRENT_TIMESTAMP
);
*/

-- =====================================================================
-- ROLE-BASED ACCESS CONTROL (RBAC)
-- =====================================================================

-- 19. Create non-login group roles only if they do not already exist.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'royaldb_dba') THEN
        CREATE ROLE royaldb_dba NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'royaldb_tech') THEN
        CREATE ROLE royaldb_tech NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'royaldb_readonly') THEN
        CREATE ROLE royaldb_readonly NOLOGIN;
    END IF;
END
$$;

-- 20. Database and schema access.
GRANT CONNECT ON DATABASE royaldb
TO royaldb_dba, royaldb_tech, royaldb_readonly;

GRANT USAGE ON SCHEMA public
TO royaldb_dba, royaldb_tech, royaldb_readonly;

-- 21. DBA privileges.
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public
TO royaldb_dba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public
TO royaldb_dba;

-- 22. Technician privileges.
GRANT SELECT ON ALL TABLES IN SCHEMA public
TO royaldb_tech;
GRANT INSERT, UPDATE ON ticket, ticket_assignment
TO royaldb_tech;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
TO royaldb_tech;

-- 23. Read-only privileges.
GRANT SELECT ON ALL TABLES IN SCHEMA public
TO royaldb_readonly;

-- 24. Verify group roles.
SELECT rolname, rolcanlogin, rolsuper
FROM pg_roles
WHERE rolname IN ('royaldb_dba', 'royaldb_tech', 'royaldb_readonly')
ORDER BY rolname;

-- NOTE:
-- Login-user CREATE ROLE statements are intentionally not included here
-- because passwords must not be stored in a project SQL file.
-- The implemented lab users were assigned to the corresponding group roles:
-- royal_dba_user      -> royaldb_dba
-- royal_tech_user     -> royaldb_tech
-- royal_readonly_user -> royaldb_readonly

-- =====================================================================
-- EXPECTED-DENIAL LEAST-PRIVILEGE TESTS
-- Run these tests only from an administrative session that is permitted
-- to SET ROLE to the test users.
-- =====================================================================

-- 25. Read-only validation.
-- SELECT should SUCCEED.
/*
SET ROLE royal_readonly_user;

SELECT ticket_id, ticket_title, ticket_status
FROM ticket
ORDER BY ticket_id;

-- EXPECTED DENIAL:
-- UPDATE should fail because the read-only role has no UPDATE privilege.
UPDATE ticket
SET ticket_status = 'Closed'
WHERE ticket_id = 1;

RESET ROLE;
*/

-- 26. Technician validation.
-- Ticket UPDATE should SUCCEED; Customer UPDATE should be DENIED.
/*
SET ROLE royal_tech_user;

-- Expected success: technician is authorized to update tickets.
UPDATE ticket
SET ticket_status = 'In Progress'
WHERE ticket_id = 5;

SELECT ticket_id, ticket_title, ticket_status
FROM ticket
WHERE ticket_id = 5;

-- EXPECTED DENIAL:
-- Technician is not authorized to modify customer records.
UPDATE customer
SET company_name = 'Unauthorized Change Test'
WHERE customer_id = 1;

RESET ROLE;
*/

-- =====================================================================
-- BACKUP / RESTORE VALIDATION NOTES
-- These are PowerShell commands, not SQL, so they remain comments here.
-- Successful backup file:
-- C:\RoyalDB_Backups\royaldb_full_2026-09-03_v2.backup
--
-- pg_dump:
-- & "C:\Program Files\PostgreSQL\18\bin\pg_dump.exe" `
--   -h localhost -p 5432 -U postgres -F c `
--   -f "C:\RoyalDB_Backups\royaldb_full_2026-09-03_v2.backup" royaldb
--
-- Restore target: royaldb_restore_test
--
-- pg_restore:
-- & "C:\Program Files\PostgreSQL\18\bin\pg_restore.exe" `
--   -h localhost -p 5432 -U postgres `
--   -d royaldb_restore_test -v `
--   "C:\RoyalDB_Backups\royaldb_full_2026-09-03_v2.backup"
--
-- Restore verification matched the source database:
-- customer=3, location=3, device=4, contract=3,
-- technician=3, ticket=5, ticket_assignment=4.
-- =====================================================================
